server.port=8080
spring.application.name=B2BProyect

spring.datasource.url=jdbc:postgresql://certificacion-server/marketplace
spring.datasource.username=root
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Parámetros de seguridad
security.jwt.token.secret-key=pQKOkAZ8j59Kb6QJC+LHL7viCOUvfhBZ7PjGeIznKbY=
#Tiempo de expiración del JWT en minutos
security.jwt.token.expire-length=480
